sql:
  sqlite3: true
  addr: ./guora.db
redis:
  addr: localhost:6379
  password:
  db: 0
admin:
  name: Guora Robot (管理员)
  mail: admin@localhost
  password: mypassword
secretkey: JustWriteSomethingWhatYouLike
lang: en
address: :8080
