db:
  driver: sqlite3
  addr: ./guora.db
redis:
  addr: redis-db:6379
  password:
  db: 0
admin:
  name: Guora Robot (管理员)
  mail: mymail
  password: mypassword
secretkey: JustWriteSomethingWhatYouLike
lang: en
address: :8080
