name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download
        sudo mkdir -p /etc/guora
        sudo cp configuration.example.yaml /etc/guora/configuration.yaml

    - name: Build
      run: go build ./cmd/guora

    - name: Test
      run: go test ./cmd/guora
