name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download
        sudo mkdir -p /etc/guora
        sudo cp configuration.example.yaml /etc/guora/configuration.yaml

    - name: Build
      run: go build ./cmd/guora

    - name: Redis in GitHub Actions
      uses: nnhy/redis-github-action@v1.0

    - name: Run coverage
      run: go test ./cmd/guora  -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    

